version: "2"
services:

    mirthconnect:
      image: mirthconnect
      container_name: mirthconnect
      depends_on:
        - mariadb
      ports:
        - 8080:8080
        - 8443:8443
        - 6661:6661

    mariadb:
      image: mariadb:latest
      container_name: mariadb
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - /home/$USER/data/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=mirthdb
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=mirth
        - MYSQL_PASSWORD=passwd
      ports:
        - 3306:3306
