version: "2"
services:

    mirthconnect:
      image: mirthminimal
      container_name: mirthconnect
      links:
        - mysql
      ports:
        - 8083:8083
        - 8443:8443

    mysql:
      image: mariadb:latest
      container_name: mariadb
      command: mysqld
      volumes:
        - /Users/$USER/data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=mirthdb
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=mirth
        - MYSQL_PASSWORD=passwd
      ports:
        - 3306:3306
